name: Run tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build test image
        run: docker build --tag tests --target test .

      - name: run tests
        run: docker run --env-file .env.test tests
